# Generated by Django 5.2 on 2026-02-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_ticket', '0002_siteoutage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteoutage',
            name='site_name',
            field=models.CharField(max_length=255),
        ),
    ]
