# Generated by Django 5.2 on 2026-02-05 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_ticket', '0003_alter_siteoutage_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteoutage',
            name='zendesk_ticket_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
