# Generated by Django 5.2 on 2026-02-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_ticket', '0004_siteoutage_zendesk_ticket_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='siteoutage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('site_name', 'is_active'), name='unique_active_site_outage'),
        ),
    ]
