# Generated by Django 5.2 on 2026-02-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_ticket', '0005_siteoutage_unique_active_site_outage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Site_name_nfmp', models.CharField(max_length=255, unique=True)),
                ('Site_name_master_db', models.CharField(max_length=255)),
            ],
        ),
    ]
