# Generated by Django 5.2 on 2026-02-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_ticket', '0006_customersites'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='siteoutage',
            name='unique_active_site_outage',
        ),
        migrations.AlterField(
            model_name='siteoutage',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='siteoutage',
            name='site_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='siteoutage',
            index=models.Index(fields=['site_name', 'is_active'], name='power_ticke_site_na_2e9c06_idx'),
        ),
        migrations.AddConstraint(
            model_name='siteoutage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('site_name',), name='unique_active_site_outage'),
        ),
    ]
